### PR TITLE
Feat: Zero-indexed tables

### PR DESCRIPTION
**Pull request by lofcz**
This PR adds an option on Script config level to index tables from zero. The option itself is implemented as `int` as it simplifies access (compared to `bool` impl). I've stated that values other than 1 & 0 are not working but we might as well throw on set if an user attempts to set the value to something else. The setting is set to 1 by default hence this is a nonbreaking change.

Some table operations have been slightly optimized. In particular I've refactored & inlined slow `GetIntegralKey` method. `If-else` nesting was reduced in several places and extraneous statements such as `else` after `return` in the branch directly above removed.

Opinionated helper property `DynValue.Int` has been added. I'm open to replace that with a better name. It's just a shorthand for `(int)DynValue.Number` which we are using all over the place.

A few overloads have been added to the `Table`. This is mostly to get consistent overloads for various functions. I intend to make a few more of these later.

I've included a new mechanism for loading test cases as the old one requires a line of manual code to be added for every new test. I can refactor old tests to be loaded in this way too.

The structure of a new test is as follows:

```
mytest.lua <-- lua source code
mytest.txt <-- expected stdout
mytest.cfg <-- might be added later as an optional file to configure lua options
```

Further commits included:
- minor cleanup of instructionloop
  - if -> lookup tables where possible
  - removed no longer needed params
  - removed redundant quantifiers
- added bench project to mock perf ideas against
- c# bumped from 7.3 to 8.0 (still netstandard 2.0 compatible)
- `CallStackItem` refactored to struct
- avoid zero length array allocations where possible
- general VM-land code cleanup

### CODE REVIEW

**Comment by CallumDev** [comment]
Four things.

1. This really needs to be split up into multiple PRs. The callstackitem, cleanup, and this zero-indexed table feature can all be separate PRs. This is a -lot- to review and a bit messy.
2. I would prefer the DynValue integer thing to be something like `CastToInteger()` since all of the other type name properties are things that a dynvalue can store exactly.
3. EmbeddedResource is not correct for the .csproj includes for your tests. See https://github.com/Librelancer/moonsharp/blob/librelancer/src/MoonSharp.Tests/MoonSharp.Tests.csproj#L20 for a way of doing a wildcard.
4. Have a look at commit 97bba70. I've added a method that allows you to do the NUnit asserts directly from the lua code. I think that would be better for your extra tests instead of having extraneous text files, keeps it clean.

**Comment by lofcz** [comment]
I agree with 1-3, will edit and split the PR accordingly.
As for 4 this is the way tests are done [over at Scriban](https://github.com/scriban/scriban/tree/master/src/Scriban.Tests/TestFiles/000-basic). Your way seems great for cases where more than stdout is needed for asserts but writing lua code out of a string has full support from IDE of choice (linter, syntax highlight, intellisense..)

**Comment by lofcz** [comment]
Zero-indexed tables extracted to #4

**Comment by CallumDev** [comment]
Done in #4 and #5

**Pull request closed without merging**
